#!/bin/bash

brew update
brew install libzip openssl libplist autoconf automake libtool autoconf-archive pkg-config
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig
git clone https://github.com/libimobiledevice/libplist
cd libplist && ./autogen.sh --without-cython && sudo make install && cd ..
cd libusbmuxd && ./autogen.sh && sudo make install && cd ..
xcrun --sdk macosx --show-sdk-path
brew install ideviceinstaller
brew install ios-deploy
pip3 install wheel
pip3 install .
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
git clone https://github.com/flutter/engine.git
