#!/bin/bash

brew update
brew install libzip openssl libplist autoconf automake libtool autoconf-archive pkg-config
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig
git clone https://github.com/libimobiledevice/libplist
cd libplist && ./autogen.sh --without-cython && sudo make install && cd ..
cd libusbmuxd && ./autogen.sh && sudo make install && cd ..
xcrun --sdk macosx --show-sdk-path
brew install ideviceinstaller
brew install ios-deploy
pip3 install wheel
pip3 install .
pip3 -m pip install gclient
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
git clone https://github.com/flutter/engine.git
ROOT_DIR=`pwd`
export PATH=$PATH:$ROOT_DIR/depot_tools
cd engine
git fetch origin $(reflutter adf563436d12ba0d50ea5beb7f3be1bb -l)
git reset --hard FETCH_HEAD
reflutter adf563436d12ba0d50ea5beb7f3be1bb -l
echo 'reflutter' > REFLUTTER
git add . && git commit -am "reflutter"
cd $ROOT_DIR
mkdir customEngine
cd customEngine
echo 'solutions = [{"managed": False,"name": "src/flutter","url": "'$ROOT_DIR/engine'","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' > .gclient
gclient sync
reflutter adf563436d12ba0d50ea5beb7f3be1bb -l
cd ..
export PATH=$PATH:`pwd`/depot_tools && sudo xcode-select -s /Applications/Xcode.app && customEngine/src/flutter/tools/gn --ios --ios-cpu=arm64 --runtime-mode=release && ninja -C customEngine/src/out/ios_release
 cp customEngine/src/out/ios_release/Flutter.framework/Flutter Flutter
